export const Data = [

    {
        id: 1,
        icon: "uil-transaction",
        title: "e-Payment / e-Banking",
        description: "Integrated multiple Electronic Payment systems for the convenience of our CMS customers.\n#Iyzico #Nexio #Garanti #SoftPoint #QNB #Yapikredi...",
        info: " Virtual POS is a payment processing solution that streamlines the use of credit and debit cards, eliminating the need for extra hardware and software and reducing associated hassles.",
        info1: "Integrated external systems payment solutions to our systems, which expanded our payment processing capabilities, providing our customers with a wide range of payment options while ensuring secure and reliable transactions",
        info2: "Developed APIs that provide our customers with comprehensive and tailored payments solutions that cater to their unique business needs, streamlining the payment process and enhancing their overall financial operations.",
        info3: "Established API services that facilitate seamless payments and secure transactions by enabling software systems to communicate and exchange payment-related information in a standardized and efficient manner.",
    },
    {
        id: 2,
        icon: "uil-keyhole-square",
        title: "e-Lock",
        description: "Integrated Electronic Entrance System to our Mobile App for our Hotels' clients usage.\n#AssaAbloy",
        info: " Assa Abloy offers products and services related to locks, doors, gates, and entrance automation. Related products and services include controlling access and confirming identities with keys, cards, tags, mobile, and bio-metric identity verification systems.",
        info1: "Implemented APIs that connects the mobile application and Assa Abloy's services, enabling our customers to access keyless entry solutions and other related services from their mobile devices, enhancing their overall experience and convenience.",
        info2: "Developed microservices that generate and provide guests with access keys, enabling them to conveniently and securely access their accommodations without the need for traditional physical keys.",
        info3: "Created services that enables seamless communication and sharing of data across our PMS, mobile application and Assa Abloy. This results in a streamlined and efficient process, providing a seamless experience for our customers and improving operational efficiency for our hospitality partners.",
    },
    {
        id: 3,
        icon: "uil-invoice",
        title: "e-Invoice / e-Archive",
        description: "Integrated Electronic Invoicing and Archiving to our PMS systems for our Hotels' usage in different countries.\n#Uyumsoft #CFDI #e-Finance #EDM #eLogo ",
        info: " Electronic invoicing refers to the process of issuing and receiving invoices in an electronic format between a supplier and a buyer.\nE-archive refers to the electronic storage and management of business documents and records in a secure, long-term digital format, this can include a variety of documents, such as invoices, contracts, financial statements, and other business-related records.",
        info1: "Established microservices that utilize various external systems like UyumSoft and eLogo that generate e-invoices and e-archive documents seamlessly, ensuring compliance with relevant regulations and providing an efficient and streamlined billing process for our clients.",
        info2: "Developed microservices that creates e-invoice (CFDI) for our mexican clients, ensuring compliance with local tax regulations and providing a streamlined invoicing process.",
        info3: "Integrated functionalities that retrieve the e-invoice and e-archive created in PDF format.",
    },
    {
        id: 4,
        icon: "uil-exchange",
        title: "Channel Managers",
        description: "Integrated Varioud Channel Managers to keep our PMS synchronized for our clients.\n#HotelRunner #SiteMinder #Phobs #Tourvisio...",
        info: " A channel manager is a software tool that allow our hotels to sell all their rooms on all their connected online booking sites at the same time, including online travel agents and direct booking channels.",
        info1: "Developed microservices that seamlessly synchronizes our PMS with multiple global channel managers, enabling us to efficiently distribute inventory and rate updates across various online travel platforms.",
        info2: "Implemented integrations that enable us to forecast hotel availability and prices accurately, allowing us to provide timely updates to channel managers and maximize revenue opportunities for our hotel partners.",
        info3: "Integrated services that seamlessly synchronize our hotel booking details with our PMS, enabling us to efficiently manage our inventory, reservations, and guest data from a centralized platform.",
    },
    {
        id: 5,
        icon: "uil-abacus",
        title: "e-Accounting",
        description: "Integrated third party Electronic Accounting Systems to our PMS.\n#Uyumsoft #Mikro",
        info: " e-Accounting refers to the use of digital technology to perform accounting functions such as bookkeeping, financial reporting, and tax compliance.\n It reduces the need for manual data entry, improves accuracy and can be accessed from anywhere with an internet connection, and many offer features such as online invoicing, payment processing, and bank reconciliation.",
        info1: "Integrated accounting services that uses multiple third party systems like Uyumsoft and Mikro.",
        info2: "Developed APIs that generate accounting records such as sales, transactions, and other related functionalities, providing our customers with comprehensive financial data that can be easily integrated into their accounting systems. This improves overall financial visibility and allows for better decision-making, enhancing the financial management capabilities of our customers.",
        info3: "Created microservices that to simplify the accounting workflow for our customers by automating various processes such as invoicing, payment reconciliation, and financial reporting. This streamlines the accounting process, reducing errors and improving overall efficiency, allowing our customers to focus on their core business activities.",
    },
    {
        id: 6,
        icon: "uil-envelope-share",
        title: "Messaging",
        description: "Integrated third party messaging providers to automate digital customer engagement.\n#d-Engage #PostaGuvercini",
        info: " A messaging provider system is a solution that facilitates the exchange of messages such as Simple Messaging Service (SMS), and e-mails between various applications or systems. It typically includes a messaging platform and associated tools and services for messaging management, monitoring, and analytics.",
        info1: "Integrated messaging providers to supply our customers with a powerful marketing tool to engage with their audience.",
        info2: "Developed integrations that offer a wide range of messaging channels, including SMS, e-mail, and messaging APIs, enabling our customers to deliver targeted and personalized messages to their audience.",
        info3: "Established services that improves the effectiveness of our customers marketing campaigns while ensuring compliance with local regulations and providing a seamless messaging experience for their clients.",
    },
]